#!/usr/bin/env bash
# Build internal/extract/code/treesitter.wasm: tree-sitter runtime + wave-1
# grammars + shim.c, compiled to WASI by zig cc. The wasm artifact is
# COMMITTED (go:embed needs it; users never run this). Re-run to refresh.
#
#   BUILD_DIR=/path scripts/wasm/build.sh    # reuse existing clones
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
BUILD_DIR="${BUILD_DIR:-$REPO_ROOT/.wasm-build}"
OUT="$REPO_ROOT/internal/extract/code/treesitter.wasm"
LOCK="$REPO_ROOT/scripts/wasm/grammars.lock"

GRAMMARS=(tree-sitter tree-sitter-go tree-sitter-python tree-sitter-javascript
          tree-sitter-typescript tree-sitter-java tree-sitter-c tree-sitter-cpp
          tree-sitter-c-sharp tree-sitter-rust tree-sitter-zig tree-sitter-sql)

# wave-2 grammars live outside the tree-sitter org (repo, extra clone args)
clone_url() {
  case "$1" in
    tree-sitter-zig)    echo "https://github.com/tree-sitter-grammars/tree-sitter-zig.git" ;;
    tree-sitter-sql)    echo "https://github.com/DerekStride/tree-sitter-sql.git" ;;
    *)                  echo "https://github.com/tree-sitter/$1.git" ;;
  esac
}

mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"
for r in "${GRAMMARS[@]}"; do
  [ -d "$r" ] || git clone --depth 1 "$(clone_url "$r")" "$r"
  # HONOR THE LOCK. `git clone --depth 1` takes whatever the DEFAULT BRANCH
  # points at today, and the provenance block below then overwrites the lock
  # with it — so the lock recorded history instead of pinning it, and a rebuild
  # silently swapped grammars underneath a committed 32MB artifact that
  # go:embeds into every binary. Measured for real on 2026-08-15: a rebuild
  # pulled tree-sitter ee0847d->0e2af0d and tree-sitter-c-sharp af29416->9150f7d
  # without a word. Set UPDATE_GRAMMARS=1 to intentionally take newer commits.
  if [ -f "$LOCK" ] && [ -z "${UPDATE_GRAMMARS:-}" ]; then
    want=$(awk -v n="$r" '$1 == n { print $2 }' "$LOCK")
    if [ -n "$want" ] && [ "$(git -C "$r" rev-parse HEAD)" != "$want" ]; then
      echo "pinning $r to locked $want"
      git -C "$r" fetch --depth 1 origin "$want"
      git -C "$r" checkout -q "$want"
    fi
  fi
done

# sql does not commit its generated parser — generate once (needs node/npx)
if [ ! -f tree-sitter-sql/src/parser.c ]; then
  (cd tree-sitter-sql && npx -y tree-sitter-cli@0.25.10 generate)
fi

# Provenance: record what we built from.
{
  echo "# generated by scripts/wasm/build.sh — commits the wasm was built from"
  for r in "${GRAMMARS[@]}"; do
    echo "$r $(git -C "$r" rev-parse HEAD)"
  done
} > "$LOCK"

# Compile each unit with ITS OWN include dir (every grammar ships its own
# tree_sitter/parser.h), then link everything into one reactor module.
OBJ="$BUILD_DIR/obj"
rm -rf "$OBJ" && mkdir -p "$OBJ"
RUNTIME_INC=(-I "tree-sitter/lib/include" -I "tree-sitter/lib/src")
CC=(zig cc -target wasm32-wasi -O2 -c)

n=0
cc_unit() { # src, extra includes...
  local src="$1"; shift
  local o="$OBJ/$((n++))-$(basename "$src").o"
  "${CC[@]}" "$@" "$src" -o "$o" &
}
cc_unit "$REPO_ROOT/internal/grammar/assets/shim.c" "${RUNTIME_INC[@]}"
cc_unit "$REPO_ROOT/scripts/wasm/langs-embedded.c" "${RUNTIME_INC[@]}"
cc_unit "tree-sitter/lib/src/lib.c" "${RUNTIME_INC[@]}"
for g in tree-sitter-go tree-sitter-python tree-sitter-javascript tree-sitter-java \
         tree-sitter-c tree-sitter-cpp tree-sitter-c-sharp tree-sitter-rust \
         tree-sitter-zig tree-sitter-sql; do
  cc_unit "$g/src/parser.c" -I "$g/src"
  [ -f "$g/src/scanner.c" ] && cc_unit "$g/src/scanner.c" -I "$g/src"
done
for sub in typescript tsx; do
  cc_unit "tree-sitter-typescript/$sub/src/parser.c" -I "tree-sitter-typescript/$sub/src"
  cc_unit "tree-sitter-typescript/$sub/src/scanner.c" -I "tree-sitter-typescript/$sub/src"
done
wait

mkdir -p "$(dirname "$OUT")"
zig cc -target wasm32-wasi -mexec-model=reactor -O2 \
  -Wl,--export-dynamic -Wl,--initial-memory=67108864 -Wl,--max-memory=1073741824 \
  "$OBJ"/*.o -o "$OUT"

ls -la "$OUT"
