package golden

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Auditable golden results: under RECORD_GOLDEN=1 every judge/corpus run
// appends one line to proof/golden/history.ndjson (append-only, one JSON
// object per run per corpus — ts, commit, scores, per-question marks) and
// rewrites proof/golden/SCOREBOARD.md (the human view of the CURRENT marks).
// Both are committed and reviewed like code, so the score trail is git
// history itself: who changed what, when, and what the marks were before.

type historyLine struct {
	TS       string             `json:"ts"`
	Commit   string             `json:"commit"`
	Kind     string             `json:"kind"` // judge | corpus
	Corpus   string             `json:"corpus"`
	Score    float64            `json:"score,omitempty"`
	Floor    float64            `json:"floor,omitempty"`
	Marks    map[string]float64 `json:"marks,omitempty"`
	Nodes    int                `json:"nodes,omitempty"`
	Edges    int                `json:"edges,omitempty"`
	GatherMS int64              `json:"gather_ms,omitempty"`
}

func recordingEnabled() bool { return os.Getenv("RECORD_GOLDEN") == "1" }

func repoRootDir() string {
	abs, err := filepath.Abs("../..")
	if err != nil {
		return "."
	}
	return abs
}

func shortHead() string {
	out, err := exec.Command("git", "rev-parse", "--short", "HEAD").Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(out))
}

// appendHistory writes one audit line; failures are surfaced by the caller's
// test, never swallowed silently into a half-written file (O_APPEND line).
func appendHistory(l historyLine) error {
	l.TS = time.Now().UTC().Format(time.RFC3339)
	l.Commit = shortHead()
	dir := filepath.Join(repoRootDir(), "proof", "golden")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	f, err := os.OpenFile(filepath.Join(dir, "history.ndjson"), os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()
	data, err := json.Marshal(l)
	if err != nil {
		return err
	}
	_, err = f.Write(append(data, '\n'))
	return err
}

// writeScoreboard rewrites the human view for one corpus section: current
// score, floor, and every question's mark with its gap note.
func writeScoreboard(corpus string, score, floor float64, qs []question, marks map[string]float64) error {
	dir := filepath.Join(repoRootDir(), "proof", "golden")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	path := filepath.Join(dir, "SCOREBOARD.md")
	sections := map[string]string{}
	if data, err := os.ReadFile(path); err == nil {
		for _, sec := range strings.Split(string(data), "\n## ") {
			if name, _, ok := strings.Cut(sec, "\n"); ok && name != "" && !strings.HasPrefix(sec, "#") {
				sections[strings.TrimSpace(name)] = "## " + sec
			}
		}
	}
	var b strings.Builder
	fmt.Fprintf(&b, "## %s\n\n", corpus)
	fmt.Fprintf(&b, "**Score %.1f / %d** (floor %.1f) — commit %s, %s\n\n", score, len(qs), floor, shortHead(), time.Now().UTC().Format("2006-01-02"))
	b.WriteString("| Q | Mark | Question | Gap note |\n|---|---|---|---|\n")
	for _, q := range qs {
		gap := q.Gap
		if gap == "" {
			gap = "—"
		}
		fmt.Fprintf(&b, "| %s | %.1f | %s | %s |\n", q.ID, marks[q.ID], q.Text, gap)
	}
	b.WriteString("\n")
	sections[corpus] = b.String()

	names := make([]string, 0, len(sections))
	for n := range sections {
		names = append(names, n)
	}
	sort.Strings(names)
	var out strings.Builder
	out.WriteString("# Golden judged scoreboard — current marks\n\n")
	out.WriteString("Regenerated by `RECORD_GOLDEN=1 task golden` (judge tier); history in\n`history.ndjson`. The floor may only move UP, in a reviewed diff.\n\n")
	for _, n := range names {
		out.WriteString(sections[n])
	}
	return os.WriteFile(path, []byte(out.String()), 0o644)
}
