// requirements.go — requirements*.txt recognizer (ADR 2026-07-25-structured-
// formats S7), plus the honesty gate that made S7 shippable.
//
// THE GATE: 61% of pypi declarations in the measured corpus come from
// requirements*.txt and 12 of 40 such files are pip-compile / uv-lock output —
// a resolved TRANSITIVE CLOSURE, not a declaration of intent. Emitting those as
// `declares` edges would be a new honesty failure (the ADR's H2), so a
// generated file is SKIPPED ENTIRELY: silence beats a wrong claim. `isLockfile`
// cannot see this — the name is `requirements.txt`, not `*.lock`.
//
// Includes (`-r other.txt`) are NOT followed: the included file is a repo file
// and gets scanned on its own, so following would double-count.
package manifests

import "strings"

// generatedMarkers are the header comments pip-compile / uv / pip-tools write
// into their output. Matched case-insensitively against the leading comment
// block only, so a hand-written file that merely mentions pip-compile in a
// note further down is unaffected.
var generatedMarkers = []string{
	"autogenerated by pip-compile", "generated by pip-compile",
	"uv pip compile", "autogenerated by uv", "generated by uv",
	"pip-compile --", "by pip-tools",
}

func extractRequirements(c *collector, rel, content string) {
	lines := strings.Split(content, "\n")
	if isGeneratedRequirements(lines) {
		return // transitive closure, not intent
	}
	scope := requirementsScope(rel)
	for _, raw := range lines {
		line := strings.TrimSpace(strings.TrimRight(raw, "\r"))
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// Option lines: -r/-c includes, -e editable installs, --hash, --index-url.
		if strings.HasPrefix(line, "-") {
			continue
		}
		if i := strings.Index(line, " #"); i >= 0 {
			line = strings.TrimSpace(line[:i])
		}
		line = strings.TrimSuffix(strings.TrimSpace(line), "\\")
		name, spec := pep508(line)
		addPypiDep(c, rel, name, spec, scope)
	}
}

// requirementsScope derives the raw scope from the FILENAME — the only signal a
// requirements file carries about its purpose (`requirements-dev.txt`,
// `requirements_test.txt`). scopeclass.go maps these to dev/test.
func requirementsScope(rel string) string {
	base := strings.ToLower(rel)
	if i := strings.LastIndexByte(base, '/'); i >= 0 {
		base = base[i+1:]
	}
	base = strings.TrimSuffix(base, ".txt")
	switch {
	case strings.Contains(base, "dev"):
		return "requirements-dev"
	case strings.Contains(base, "test"):
		return "requirements-test"
	}
	return "requirements"
}

// isGeneratedRequirements detects pip-compile/uv output two ways, either
// sufficient:
//
//  1. HEADER — a generated-by marker inside the leading comment block.
//  2. SHAPE — the file carries `--hash=` lines AND every requirement in it is
//     fully `==`-pinned. Only a resolver writes hashes.
//
// Residual risk, stated rather than hidden: a HAND-WRITTEN, fully pinned
// requirements.txt WITHOUT hashes is kept (correct — it is a declaration), and
// a hand-written file that carries hashes and is fully pinned is skipped (a
// false positive we accept: it is indistinguishable from resolver output by
// content, and under-claiming is the house rule).
func isGeneratedRequirements(lines []string) bool {
	for _, raw := range lines {
		line := strings.TrimSpace(strings.TrimRight(raw, "\r"))
		if line == "" {
			continue
		}
		if !strings.HasPrefix(line, "#") {
			break // leading comment block is over
		}
		low := strings.ToLower(line)
		for _, m := range generatedMarkers {
			if strings.Contains(low, m) {
				return true
			}
		}
	}
	hashes, reqs, pinned := false, 0, 0
	for _, raw := range lines {
		line := strings.TrimSpace(strings.TrimRight(raw, "\r"))
		if strings.Contains(line, "--hash=") {
			hashes = true
		}
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "-") {
			continue
		}
		if i := strings.Index(line, " #"); i >= 0 {
			line = strings.TrimSpace(line[:i])
		}
		line = strings.TrimSuffix(strings.TrimSpace(line), "\\")
		if name, spec := pep508(line); name != "" {
			reqs++
			if strings.HasPrefix(spec, "==") {
				pinned++
			}
		}
	}
	return hashes && reqs > 0 && reqs == pinned
}
