package manifests

import (
	"strings"
	"testing"
)

const fixtureRequirements = `# runtime deps for the service
-r base.txt
--index-url https://example.invalid/simple
-e .

flask>=2.3          # the web framework
celery[redis]==5.2.7
gha-update ; python_full_version >= '3.12'
typing_extensions

git+https://example.invalid/x#egg=xpkg
https://example.invalid/direct.whl
`

func TestRequirementsTxt(t *testing.T) {
	b := extractFixture(t, map[string]string{"requirements.txt": fixtureRequirements})
	rel := "requirements.txt"

	mustDecl(t, b, rel, "dep:pypi/flask|>=2.3|requirements")
	mustDecl(t, b, rel, "dep:pypi/celery|==5.2.7|requirements")
	mustDecl(t, b, rel, "dep:pypi/gha-update||requirements")
	mustDecl(t, b, rel, "dep:pypi/typing-extensions||requirements")

	if got := len(declared(b, rel)); got != 4 {
		t.Errorf("declarations = %d, want 4 (options/includes/VCS+URL refs skipped):\n  %s",
			got, strings.Join(declared(b, rel), "\n  "))
	}
	for _, bad := range []string{"dep:pypi/git", "dep:pypi/https", "dep:pypi/base", "dep:pypi/e"} {
		if nodeByID(b, bad) != nil {
			t.Errorf("phantom dep from an option/URL line: %s", bad)
		}
	}
	for _, e := range b.Edges {
		if e.Relation == "declares" && e.Metadata["scope_class"] != "runtime" {
			t.Errorf("plain requirements.txt scope_class = %q, want runtime", e.Metadata["scope_class"])
		}
	}
}

// The filename is the only signal a requirements file carries about purpose.
func TestRequirementsScopeFromFilename(t *testing.T) {
	for name, wantScope := range map[string]string{
		"requirements.txt":       "requirements",
		"requirements-dev.txt":   "requirements-dev",
		"requirements_test.txt":  "requirements-test",
		"requirements-tests.txt": "requirements-test",
	} {
		if got := requirementsScope("a/b/" + name); got != wantScope {
			t.Errorf("requirementsScope(%s) = %q, want %q", name, got, wantScope)
		}
	}
	b := extractFixture(t, map[string]string{
		"requirements-dev.txt":  "pytest\n",
		"requirements-test.txt": "coverage\n",
	})
	mustDecl(t, b, "requirements-dev.txt", "dep:pypi/pytest||requirements-dev")
	mustDecl(t, b, "requirements-test.txt", "dep:pypi/coverage||requirements-test")
	for _, e := range b.Edges {
		if e.Source == "requirements-dev.txt" && e.Metadata["scope_class"] != "dev" {
			t.Errorf("dev file scope_class = %q", e.Metadata["scope_class"])
		}
		if e.Source == "requirements-test.txt" && e.Metadata["scope_class"] != "test" {
			t.Errorf("test file scope_class = %q", e.Metadata["scope_class"])
		}
	}
}

// The honesty gate: pip-compile output is a resolved transitive closure, not a
// declaration. It must contribute ZERO dependency nodes and ZERO edges.
const fixturePipCompileLock = `#
# This file is autogenerated by pip-compile with Python 3.11
# by the following command:
#
#    pip-compile --resolver=backtracking pyproject.toml
#
amqp==5.1.1
    # via kombu
blinker==1.6.2
    # via flask
click==8.1.3
    # via
    #   celery
    #   flask
werkzeug==2.3.3
    # via flask
`

func TestPipCompileLockContributesNothing(t *testing.T) {
	b := extractFixture(t, map[string]string{"requirements.txt": fixturePipCompileLock})
	if len(b.Nodes) != 0 || len(b.Edges) != 0 {
		t.Fatalf("pip-compile lock must yield nothing, got %d nodes %d edges: %+v",
			len(b.Nodes), len(b.Edges), b.Nodes)
	}
}

func TestGeneratedRequirementsDetection(t *testing.T) {
	cases := map[string]bool{
		fixturePipCompileLock: true,
		// uv's header.
		"# This file was autogenerated by uv via the following command:\n#    uv pip compile\nflask==2.0\n": true,
		// Hash-carrying, fully pinned: only a resolver writes hashes.
		"flask==2.3.3 \\\n    --hash=sha256:aaa\nclick==8.1.3 \\\n    --hash=sha256:bbb\n": true,
		// Hand-written, fully pinned, NO hashes — a real declaration, kept.
		"flask==2.3.3\nclick==8.1.3\n": false,
		// Hashes present but not everything pinned — not resolver output.
		"flask>=2.3 \\\n    --hash=sha256:aaa\n": false,
		// A note mentioning pip-compile below the header block does not count.
		"flask>=2.3\n# regenerate with pip-compile --upgrade\n": false,
		"":                          false,
		"# just a comment\nflask\n": false,
	}
	for content, want := range cases {
		if got := isGeneratedRequirements(strings.Split(content, "\n")); got != want {
			t.Errorf("isGeneratedRequirements(%q) = %v, want %v", content, got, want)
		}
	}
}

func TestPythonRustManifestKinds(t *testing.T) {
	for name, want := range map[string]string{
		"pyproject.toml":        "pyproject",
		"Cargo.toml":            "cargo",
		"cargo.toml":            "cargo",
		"requirements.txt":      "requirements",
		"requirements-dev.txt":  "requirements",
		"requirements_test.txt": "requirements",
		"constraints.txt":       "",
		"setup.py":              "",
		"Cargo.lock":            "", // a lock is not a manifest kind at all
	} {
		if got := manifestKind(name); got != want {
			t.Errorf("manifestKind(%s) = %q, want %q", name, got, want)
		}
	}
	if !isLockfile("Cargo.lock") || !isLockfile("poetry.lock") || !isLockfile("uv.lock") {
		t.Error("Cargo.lock/poetry.lock/uv.lock must be refused")
	}
	// uv.lock and Cargo.lock reach the walk but are refused before parsing.
	b := extractFixture(t, map[string]string{
		"Cargo.lock": "[[package]]\nname = \"serde\"\nversion = \"1.0\"\n",
		"uv.lock":    "[[package]]\nname = \"flask\"\nversion = \"3.0\"\n",
	})
	if len(b.Nodes) != 0 {
		t.Fatalf("lock files must yield nothing, got %+v", b.Nodes)
	}
}
